name: C:\Users\t000587\AppData\Local\Continuum\Miniconda\envs\fsiox
dependencies:
- pip=8.1.2=py35_0
- python=3.5.2=0
- setuptools=23.0.0=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - click==6.6
  - flask==0.11.1
  - flask-socketio==2.5
  - gevent==1.1.1
  - greenlet==0.4.10
  - itsdangerous==0.24
  - jinja2==2.8
  - markupsafe==0.23
  - python-engineio==0.9.2
  - python-socketio==1.4.1
  - requests==2.10.0
  - six==1.10.0
  - socketio-client==0.6.6
  - websocket-client==0.37.0
  - werkzeug==0.11.10

